defaults:
    - override hydra/launcher: submitit_local

# environment
#task: humanoid_h1-sit_simple-v0
task: humanoid_h1-walk-v0
obs: state
#exp_name: param_perturb-ucb-H=8-real_ensemble-10
exp_name: -coef_r1_v1_c1-rho1-H8-l2r0-history_0
#agent_name: SSM_agent_v15_const
agent_name: SSM_agent_v46

# evaluation
checkpoint: ???
eval_episodes: 1
eval_freq: 10000

# training
steps: 10_000_000
device: cuda
replay_device: cuda
batch_size: 256
reward_coef: 1
value_coef: 1
consistency_coef: 1
rho: 1
lr: 3e-4
num_updates: 1
l2_regularizer: 0
enc_lr_scale: 0.3
grad_clip_norm: 20
tau: 0.01
discount_denom: 5
param_noise_std: 2e-1
discount_min: 0.95
discount_max: 0.995
buffer_size: 3_000_000
reward_priority_sampling: false
reward_priority_alpha: 0.6
reward_priority_beta: 0.0
reward_priority_eps: 1e-3
reward_priority_uniform_mix: 0.1
reward_priority_max_index_size: 50_000_000
seed_steps: 5000
data_dir: ???

# ssm agent
num_ensembles: 10
dynamics_ensemble_noise_scale: 0.1
dynamics_a_num_bases: 16

# ssm transformer
transformer_d_model: 128
transformer_num_heads: 4
transformer_dff: 512
transformer_num_layers: 6
transformer_dropout: 0.1
history_horizon: 1

# ssm controller
apply_action_constraints: true
jax_mpc_platform: cpu
jax_mpc_preallocate: false
jax_mpc_mem_fraction: 0.20
jax_mpc_disable_cuda_after_error: true
mpc_convex_num_iters: 64
mpc_convex_step_size: 0.03
mpc_convex_action_l2: 0.0

# planning
solver: jax_projected_adam
mpc: true
iterations: 6
num_samples: 512
horizon: 8
control_horizon: 8
min_std: 0.05
max_std: 2
temperature: 0.5
u_penalty: 0

# actor
log_std_min: -10
log_std_max: 2
entropy_coef: 1e-4

# critic
num_bins: 101
vmin: -10
vmax: +10


# architecture
model_size: ???
num_enc_layers: 2
enc_dim: 256
num_channels: 32

mlp_dim: 512
latent_dim: 256
task_dim: 96
num_q: 5
dropout: 0.1
simnorm_dim: 8
policy_struct: [256, 256]
encoder_struct: [512, 512]

# logging
wandb_project: humanoid-bench
wandb_entity: minghao-han
wandb_silent: false
disable_wandb: false
save_csv: true

# misc
save_video: false
save_agent: true
seed: 1

# convenience
work_dir: ???
task_title: ???
multitask: ???
tasks: ???
obs_shape: ???
action_dim: ???
episode_length: ???
obs_shapes: ???
action_dims: ???
episode_lengths: ???

bin_size: ???

# humanoid envs
policy_path: ???
mean_path: ???
var_path: ???
policy_type: ???
small_obs: ???
