defaults:
    - override hydra/launcher: submitit_local

# environment
task: humanoid_h1-sit_simple-v0
obs: state
#exp_name: param_perturb-ucb-H=8-real_ensemble-10
exp_name: H=16-no_discount_plan
#agent_name: SSM_agent_v15_const
agent_name: SSM_agent_v18

# evaluation
checkpoint: ???
eval_episodes: 1
eval_freq: 10000

# training
steps: 10_000_000
batch_size: 256
reward_coef: 1.0
value_coef: 1e0
consistency_coef: 1e-2
rho: 1.0
lr: 3e-4
enc_lr_scale: 0.3
grad_clip_norm: 20
tau: 0.01
discount_denom: 5
discount_min: 0.95
discount_max: 0.995
buffer_size: 3_000_000

data_dir: ???

# ssm agent
num_ensembles: 10



# ssm transformer
transformer_d_model: 128
transformer_num_heads: 4
transformer_dff: 512
transformer_num_layers: 6
transformer_dropout: 0.1
history_horizon: 6

# ssm controller
apply_action_constraints: true

# planning
solver: SCS
mpc: true
iterations: 6
num_samples: 512
horizon: 16
control_horizon: 8
min_std: 0.05
max_std: 2
temperature: 0.5
u_penalty: 1e-2

# actor
log_std_min: -10
log_std_max: 2
entropy_coef: 1e-4

# critic
num_bins: 101
vmin: -10
vmax: +10


# architecture
model_size: ???
num_enc_layers: 2
enc_dim: 256
num_channels: 32
mlp_dim: 512
latent_dim: 512
task_dim: 96
num_q: 5
dropout: 0.01
simnorm_dim: 8
policy_struct: [256, 256]
encoder_struct: [512, 512]

# logging
wandb_project: humanoid-bench
wandb_entity: minghao-han
wandb_silent: false
disable_wandb: false
save_csv: true

# misc
save_video: true
save_agent: true
seed: 1

# convenience
work_dir: ???
task_title: ???
multitask: ???
tasks: ???
obs_shape: ???
action_dim: ???
episode_length: ???
obs_shapes: ???
action_dims: ???
episode_lengths: ???
seed_steps: ???
bin_size: ???

# humanoid envs
policy_path: ???
mean_path: ???
var_path: ???
policy_type: ???
small_obs: ???
